### ISSUE TITLE
A11y review

### ISSUE THREAD

**Issue by martndemus** [martndemus/ember-form-for#48]
I've been trying to make ember-form-for as a11y friendly as possible, but I'm no expert.
I'd love for someone more seasoned with a11y to review the addon.

**Comment by nathanhammond** [comment]
nathanhammond [12:01] 
So, your error handling has a few issues.

[12:03] 
`described-by` is a space separated list of ID refs, so you would ideally link the input field and the error(s) together.

martndemus [12:04 PM] 
So each error meesage should have an ID and the described-by should have each of those IDs as a list?

nathanhammond [12:04 PM] 
Correct.

[12:05] 
Theoretically you should also have a list of all errors consolidated in one place at the top of the page/form as well.

martndemus [12:05 PM] 
That's possible, should that be visually hidden?

nathanhammond [12:05 PM] 
No.

[12:06] 
Submission of the form should trigger that behavior. Inline validation doesn't need the collection of error messages up at the top.

martndemus [12:06 PM] 
Ah like that

nathanhammond [12:07 PM] 
Submission of the form should, on error, probably set focus to the form itself as the container of "hey, all this changed."

[12:08] 
Which would dump the user back to the top and be able to see the list of all error messages.

martndemus [12:08 PM] 
so `$('form').focus()` ?

nathanhammond [12:08 PM] 
Yeah, but you'll need to add a `tabindex=-1` to the form to make it possible to focus.

[12:08] 
\(it's inert by default)

[12:09] 
Good work on the hints, by the way, they're exactly as they should be. :slightly_smiling_face:

[12:10] 
And, I tend to like my error messages at the top to be `label` elements so that you can immediately jump to the form element.

martndemus [12:10 PM] 
Never heard of the being `label` elements

nathanhammond [12:11 PM] 
Has weird reading behavior, so you'd drop the inline error described-by in that scenario.

martndemus [12:11 PM] 
That's so cool and so obvious now you tell me

nathanhammond [12:12 PM] 
:smile: It's one of my favorite examples of how building an accessible website can makes usability better for everybody.

martndemus [12:13 PM] 
Awesome, I am going to write this up in the GH issue and get down to it :slightly_smiling_face:

**Comment by hvgotcodes** [comment]
I'm curious as to the progress on accessibility in forms.  Is there a list of AX concerns that are functional and a list of those that are planned?
